-- GENERAR LA BASE DE DATOS IMPORTACION
DROP DATABASE IF EXISTS IMPORTACION;
CREATE DATABASE IMPORTACION;
USE IMPORTACION;

-- CREAR LAS TABLAS DE LA BASE DE DATOS
CREATE TABLE PRODUCTO(
   producto_id INT NOT NULL AUTO_INCREMENT,
   nombre VARCHAR(200),
   dimensiones VARCHAR(20) NOT NULL DEFAULT "100X100",
   codigo VARCHAR(12),
   categoria_id INT,
   PRIMARY KEY(producto_id)
);
CREATE TABLE CATEGORIA(
   categoria_id INT NOT NULL AUTO_INCREMENT,
   nombre VARCHAR(200) NOT NULL,
   codigo_interno VARCHAR(12),
   estado_produccion BOOL,
   PRIMARY KEY(categoria_id)
);
-- INCORPORAR LAS RELACIONES
ALTER TABLE PRODUCTO
   ADD CONSTRAINT fk_producto_catergoria
   FOREIGN KEY (categoria_id) REFERENCES CATEGORIA(categoria_id)
;

-- INCORPORAR DATOS A LAS TABLAS

